### ISSUE TITLE
Font size larger than editor

### ISSUE THREAD

**Issue by craigmdennis** [Glavin001/atom-coffeescript-preview#11]
Great package, very useful.

When I trigger the preview, the font size is always bigger than the actual editor. I know there seems to have been an issue with this in the past with issue #5 and #6 but I'm not sure if this is related.

Let me know what you need to diagnose / fix this.

![screen shot 2014-07-26 at 14 48 50](https://cloud.githubusercontent.com/assets/725067/3712361/de4b2a84-150e-11e4-8c98-ba9c066a4970.png)

**Comment by Glavin001** [comment]
Thanks, @craigmdennis!

I am moving over to [`Preview` for Atom](https://github.com/Glavin001/atom-preview) which supports CoffeeScript and much, much more.
Your issue will continue from here: https://github.com/Glavin001/atom-preview/issues/25

Please uninstall `coffeescript-preview` and install `preview` in Atom, and I'll be working on your issue soon :).

Thanks again for your support!

**Comment by craigmdennis** [comment]
Ok, will do.
