### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by tautologistics** [Glavin001/atom-coffeescript-preview#16]
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager

**Comment by ddavison** [comment]
this package is no longer maintained - see https://atom.io/packages/coffeescript-preview

**Comment by Glavin001** [comment]
Use https://github.com/Glavin001/atom-preview

**Comment by ddavison** [comment]
oops .. :+1: i knew that

**Comment by Glavin001** [comment]
What is interesting is that anyone who has updated should be seeing a big annoying message telling them to upgrade to Preview and that CoffeeScript-Preview is deprecated. Of course, any user should be up-to-date before creating Issues. So therefore it leaves me confused as to why every now and then I receive new Issues in this repo :P.
I will be unpublishing soon when Atom v1.0 comes out in a few days.
