### ISSUE TITLE
Package Loading slow

### ISSUE THREAD

**Issue by yongkangchen** [Glavin001/atom-coffeescript-preview#2]
![2014-07-09 9 44 22](https://cloud.githubusercontent.com/assets/704762/3525009/30773b0c-076f-11e4-9b51-10a9191f713d.png)

considering use activationEvents to delay loading.

```
activationEvents (Optional): an Array of Strings identifying events that trigger your package's activation. You can delay the loading of your package until one of these events is triggered.
```

**Comment by Glavin001** [comment]
+1 Will do. Thank you for the heads up.

**Comment by Glavin001** [comment]
My original loading time was about 90ms and now is 7ms.

**Comment by yongkangchen** [comment]
Yeah! :+1:
