### ISSUE TITLE
Update preview when change tab 

### ISSUE THREAD

**Issue by yongkangchen** [Glavin001/atom-coffeescript-preview#3]
Hope for this feature.

**Comment by Glavin001** [comment]
Could you elaborate a little more?

**Comment by yongkangchen** [comment]
![coffeescript-preview](https://cloud.githubusercontent.com/assets/704762/3541654/6e8b44b2-084e-11e4-9680-ba8b3d1b857b.gif)

I mean, when I switch file, the preview can auto update to show new file, will better for me.

**Comment by Glavin001** [comment]
Looks like this would actually be do-able!
http://discuss.atom.io/t/is-there-an-event-triggered-when-tabs-are-changed-active-editor-changes/5418/2

Great idea!

**Comment by Glavin001** [comment]
Somewhat unrelated question, what are you using for recording and creating that animated .gif, @yongkangchen ?

**Comment by yongkangchen** [comment]
[licecap](http://www.cockos.com/licecap/)

**Comment by Glavin001** [comment]
Ahh, you're on Windows. I found [gitgrabber](http://www.gifgrabber.com/) that works on my Mac but I am always interested to see the other tools other developers use. Thanks!

**Comment by yongkangchen** [comment]
I am mac ox 10.9.3  :cry:  http://www.cockos.com/licecap/licecap124.dmg

**Comment by Glavin001** [comment]
OH wow I read the requirements and it said Windows and the screenshot was Windows and somehow completely missed the Mac requirement right below :P. Thanks!!

**Comment by Glavin001** [comment]
@yongkangchen just released 0.2.0 with this feature :). Enjoy!

**Comment by yongkangchen** [comment]
Nice ~

**Comment by Glavin001** [comment]
Bug: title does not also update.
- [x] Update Title on tab change

**Comment by Glavin001** [comment]
- [x] Listening for `content-modified` events on the new tab (still listening for change events on old tab)

**Comment by Glavin001** [comment]
![animated_screenshot](https://cloud.githubusercontent.com/assets/1885333/3576573/99212e10-0b93-11e4-8cd5-9da29e9230dd.gif)
