### ISSUE TITLE
Follow scroll of CoffeeScript tab and sync to JS tab

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-coffeescript-preview#4]
Follow scroll of CoffeeScript tab and sync to JS tab

**Comment by Frozenfire92** [comment]
+1 much needed :)

**Comment by Glavin001** [comment]
This is becoming difficult..

Getting total height of clipped element: http://stackoverflow.com/a/5627286/2578205

**Comment by Glavin001** [comment]
Looks like the `height` of the `scroll-view` element is fixed to be larger and dynamically recalculated on Atom's scrolling.
![image](https://cloud.githubusercontent.com/assets/1885333/3566826/fca7a020-0b04-11e4-8f11-469e96210015.png)

This is likely internally handled by Atom. Will research into Atom source code later.

**Comment by Glavin001** [comment]
@kevinsawicki would you be able to point me in the right direction for this? I am trying to determine where the Editor has scrolled to. I was trying to get the `scrollHeight` of the `scroll-view` however (as shown above) it seems that the height is forced to be bigger (`height: 5700px`) than the actual content and so the numbers do not add up. Any help would be greatly appreciated!

**Comment by kevinsawicki** [comment]
The `Editor` class has a `getScrollTop` method that should work for this I would think.

**Comment by Glavin001** [comment]
Great! I'll take a look. Thanks, again!

**Comment by Glavin001** [comment]
Continuing on new package here: https://github.com/Glavin001/atom-preview/issues/26
