### ISSUE TITLE
Not using active syntax theme

### ISSUE THREAD

**Issue by batjko** [Glavin001/atom-coffeescript-preview#5]
Hi,

This is a great package.
One little issue to note would be that the preview doesn't seem to use the actual syntax theme, in terms of the font and colors:
![image](https://cloud.githubusercontent.com/assets/7287076/3568938/fed5c6dc-0b37-11e4-88ce-b1cfbdb30687.png)

Any chance this can be adopted?

**Comment by Glavin001** [comment]
> Any chance this can be adopted?

Absolutely. I originally tried to get https://github.com/atom/highlights working however it complained with errors when I installed it so I used another package, see #1. Maybe @kevinsawicki could give me a hand in where I should look for how the EditorView renders syntax highlighting :).

**Comment by kevinsawicki** [comment]
There is an API on the `EditorView` to build HTML for a given text chunk using the current theme.

The Markdown preview package uses it to colorize code blocks in markdown files.

You can get the JS grammar by doing `atom.syntax.grammarForScopeName('source.js')` and then do the following to build the HTML: https://github.com/atom/markdown-preview/blob/17dd86ede2d6a270fecc39b696282937c67fb3ae/lib/renderer.coffee#L97-L100

Is this what you are looking for?

**Comment by Glavin001** [comment]
Looks like exactly what I need! Thank you @kevinsawicki!
I should be able to whip this up quickly later tonight :).

**Comment by kevinsawicki** [comment]
Great, let me know if you have any issues, very cool package :+1:

**Comment by batjko** [comment]
Great stuff! Thank you both.

**Comment by Glavin001** [comment]
Pushed :).
![screenshot](https://raw.githubusercontent.com/Glavin001/atom-coffeescript-preview/master/screenshot.png)

**Comment by batjko** [comment]
Yup, that looks pretty now!

The font size isn't catching up yet, but the theme is working very nicely now!
![image](https://cloud.githubusercontent.com/assets/7287076/3577411/78ddde88-0b9c-11e4-8b57-a5ac8382c496.png)

**Comment by Glavin001** [comment]
Whaaat? I even fixed the font-size before I pushed. It updates the font-size every time it renders the new preview.
https://github.com/Glavin001/atom-coffeescript-preview/blob/master/lib/coffeescript-preview-view.coffee#L135-L141

@kevinsawicki any ideas / alternatives to syncing the font-size?

**Comment by batjko** [comment]
Sorry, mate.
I tried closing the preview, then changing the coffee's size, then re-loading the preview, still not adapting.

No errors in the console, btw.

**Comment by Glavin001** [comment]
Just tried it with mine. It is working, because the tab change event is triggered when I got back from Atom Settings tab back to the coffeescript editor, and it reloads the view and re-applies the font-size.

How are you setting the font size?

**Comment by Glavin001** [comment]
@batjko I think I may have found the problem. And also a solution. Continuing with issue #6

**Comment by batjko** [comment]
Ah, yea I'm not using the settings view for it, rather the `Ctrl+=` and `Ctrl+-` key binding for adjusting the size.
But even changing it in the Settings View doesn't do it for the preview.

**Comment by Glavin001** [comment]
@batjko I have pushed and published a patch that fixes the issues you described and I tested with `Ctrl+=` and `Ctrl+-` key binding for adjusting the size. Hope it works well for you, too :).

**Comment by batjko** [comment]
Yup, now it changes font size as I change it. Purrs like a kitten!
Well done, and thanks for the quick turn-around!

**Comment by Glavin001** [comment]
You're very welcome! Thank you for your support and let me know if you have any other ideas to make it even better!

**Comment by violet-athena** [comment]
Hi guys, this works fine for the inbuilt themes of Atom, but when trying something different (Monokai) it just shows grey text. Any idea where the problem might be?

**Comment by Glavin001** [comment]
@daniocean, like this? 
![image](https://cloud.githubusercontent.com/assets/1885333/3688382/9e015352-1335-11e4-9716-8c2560fac432.png)

**Comment by violet-athena** [comment]
Yes, exactly :)

**Comment by Glavin001** [comment]
I have been using the `editor-colors` class, and these other themes that are not working appear to be just using `editor` with `editor-colors`. However, it could also be an issue with the latest Atom updates -- I am finding that the font-size is also incorrectly rendered now even though the CSS says `font-size: 16px` for both.

![image](https://cloud.githubusercontent.com/assets/1885333/3688797/f0df1132-1339-11e4-9bf2-7cf7bd49b73a.png)

**Comment by Glavin001** [comment]
Tested Themes:
- [x] Atom Dark
- [x] Base16
- [x] Monokai
- [x] Solarized Dark

**Comment by Glavin001** [comment]
@daniocean just published a patch. Let me know if it works for you as well.

**Comment by Glavin001** [comment]
Also, I recommend everyone slowly migrates over to using https://github.com/Glavin001/atom-preview :).

**Comment by violet-athena** [comment]
Works great, thanks!

I'll probably move to "preview" as soon as this fix is in it :)

Cheers!

**Comment by Glavin001** [comment]
Excellent!

Sounds good. I'll have to make the fix on `Preview` later tonight after work.

Continued development will likely only continue on with `Preview` and deprecate CoffeeScript-Preview very soon.

Thanks for your support! Enjoy.
