### ISSUE TITLE
Implement a delay for Update On Tab Change

### ISSUE THREAD

**Issue by jordanbtucker** [Glavin001/atom-coffeescript-preview#8]
Enhancement request to implement a (configurable) delay for Update On Tab Change. I see too many compilation errors because I pause too long after typing an operator. Thanks.

**Comment by Glavin001** [comment]
Just published patch. Hopefully this will help diminishes those occurrences :). See https://github.com/Glavin001/atom-coffeescript-preview#package-settings for documentation on this new feature. Thanks!

**Comment by jordanbtucker** [comment]
Hmm, this isn't quite working as expected. If I set a value of, say, 3000, I should be able to make a change in the editor, and nothing should happen in the preview pane for 3 seconds. After those three seconds, it should update the preview pane (unless, of course, I've made another change in the meantime).

Instead, if I make a change, after only about half a second, the preview pane shows the loading logo and continues to show that logo for 3 seconds before it finally refreshes its output. This gives the impression that it's taking 3 seconds just to render the code.

If I set a smaller value, even 0, I still get a flash of the logo while it's loading. I don't remember there being a flash before this patch. Maybe I'm just being picky, but I think this still has room for improvement. Thanks.

**Comment by Glavin001** [comment]
How is it now?

**Comment by jordanbtucker** [comment]
This is working perfectly now! Thanks!

**Comment by Glavin001** [comment]
You're very welcome. Enjoy :)!
